DROP DATABASE `ATHENA-Test`;
DROP DATABASE `ATHENA-Tix`;
DROP DATABASE `ATHENA-Stage`;
DROP DATABASE `ATHENA-People`;
DROP DATABASE `ATHENA-Orders`;
DROP DATABASE `ATHENA-Security`;
DROP DATABASE `ATHENA-Audit`;