SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL';

DROP SCHEMA IF EXISTS `ATHENA-Tix` ;
CREATE SCHEMA IF NOT EXISTS `ATHENA-Tix` ;
USE `ATHENA-Tix`;

-- -----------------------------------------------------
-- Table `ATHENA-Tix`.`PROP_FIELDS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ATHENA-Tix`.`PROP_FIELDS` ;

CREATE  TABLE IF NOT EXISTS `ATHENA-Tix`.`PROP_FIELDS` (
  `id` BIGINT NOT NULL AUTO_INCREMENT ,
  `valueType` VARCHAR(45) NULL DEFAULT NULL ,
  `name` VARCHAR(45) NULL DEFAULT NULL ,
  `strict` TINYINT(1) NULL DEFAULT false ,
  PRIMARY KEY (`id`) )
ENGINE = InnoDB;

CREATE INDEX `fk_PROP_FIELDS_valueType_id_to_ValueTypes_id` ON `ATHENA-Tix`.`PROP_FIELDS` (`valueType` ASC) ;


-- -----------------------------------------------------
-- Table `ATHENA-Tix`.`PROP_VALUES`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ATHENA-Tix`.`PROP_VALUES` ;

CREATE  TABLE IF NOT EXISTS `ATHENA-Tix`.`PROP_VALUES` (
  `id` BIGINT NOT NULL AUTO_INCREMENT ,
  `PROP_FIELD_ID` BIGINT NULL DEFAULT NULL ,
  `propValue` VARCHAR(45) NULL DEFAULT NULL ,
  PRIMARY KEY (`id`) ,
  CONSTRAINT `fk_PropertyValues_PROP_FIELD_ID_to_PropertyFields_id`
    FOREIGN KEY (`PROP_FIELD_ID` )
    REFERENCES `ATHENA-Tix`.`PROP_FIELDS` (`id` )
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_PropertyValues_PROP_FIELD_ID_to_PropertyFields_id` ON `ATHENA-Tix`.`PROP_VALUES` (`PROP_FIELD_ID` ASC) ;


-- -----------------------------------------------------
-- Table `ATHENA-Tix`.`TICKETS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ATHENA-Tix`.`TICKETS` ;

CREATE  TABLE IF NOT EXISTS `ATHENA-Tix`.`TICKETS` (
  `id` BIGINT NOT NULL AUTO_INCREMENT ,
  `name` VARCHAR(45) NULL DEFAULT NULL ,
  PRIMARY KEY (`id`) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ATHENA-Tix`.`TICKET_PROPS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ATHENA-Tix`.`TICKET_PROPS` ;

CREATE  TABLE IF NOT EXISTS `ATHENA-Tix`.`TICKET_PROPS` (
  `id` BIGINT NOT NULL AUTO_INCREMENT ,
  `PROP_FIELD_ID` BIGINT NOT NULL ,
  `TICKET_ID` BIGINT NULL DEFAULT NULL ,
  `propType` VARCHAR(15) NULL DEFAULT NULL ,
  `valueString` VARCHAR(45) NULL DEFAULT NULL ,
  `valueInteger` INT NULL DEFAULT NULL ,
  `valueDateTime` DATETIME NULL DEFAULT NULL ,
  `valueBoolean` TINYINT(1) NULL DEFAULT NULL ,
  PRIMARY KEY (`id`) ,
  CONSTRAINT `fk_TICKET_PROPS_TICKET_ID_to_TICKETS_id`
    FOREIGN KEY (`TICKET_ID` )
    REFERENCES `ATHENA-Tix`.`TICKETS` (`id` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TICKET_PROPS_PROP_FIELD_ID_to_PROP_FIELDS__id`
    FOREIGN KEY (`PROP_FIELD_ID` )
    REFERENCES `ATHENA-Tix`.`PROP_FIELDS` (`id` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_TICKET_PROPS_TICKET_ID_to_TICKETS_id` ON `ATHENA-Tix`.`TICKET_PROPS` (`TICKET_ID` ASC) ;

CREATE INDEX `fk_TICKET_PROPS_PROP_FIELD_ID_to_PROP_FIELDS__id` ON `ATHENA-Tix`.`TICKET_PROPS` (`PROP_FIELD_ID` ASC) ;



SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
